# Generated by Django 5.2.6 on 2025-09-17 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jerseys'), ('shorts', 'Shorts'), ('shoes', 'Football Boots'), ('socks', 'Socks'), ('ball', 'Football'), ('goalkeeper', 'Goalkeeper Gear'), ('training', 'Training Equipment'), ('bag', 'Bags'), ('accessories', 'Accessories'), ('fan_merch', 'Fan Merchandise')], default='jersey'),
        ),
    ]
